
package client_gen;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "MySQLException", targetNamespace = "http://server/")
public class MySQLException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SqlFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public MySQLException(String message, SqlFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public MySQLException(String message, SqlFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: client_gen.SqlFault
     */
    public SqlFault getFaultInfo() {
        return faultInfo;
    }

}
