
package client_gen;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GodService", targetNamespace = "http://server/", wsdlLocation = "http://localhost:8080/hello?wsdl")
public class GodService
    extends Service
{

    private final static URL GODSERVICE_WSDL_LOCATION;
    private final static WebServiceException GODSERVICE_EXCEPTION;
    private final static QName GODSERVICE_QNAME = new QName("http://server/", "GodService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GODSERVICE_WSDL_LOCATION = url;
        GODSERVICE_EXCEPTION = e;
    }

    public GodService() {
        super(__getWsdlLocation(), GODSERVICE_QNAME);
    }

    public GodService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GODSERVICE_QNAME, features);
    }

    public GodService(URL wsdlLocation) {
        super(wsdlLocation, GODSERVICE_QNAME);
    }

    public GodService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GODSERVICE_QNAME, features);
    }

    public GodService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GodService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LabWebService
     */
    @WebEndpoint(name = "LabWebServicePort")
    public client_gen.LabWebService getLabWebServicePort() {
        return super.getPort(new QName("http://server/", "LabWebServicePort"), client_gen.LabWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LabWebService
     */
    @WebEndpoint(name = "LabWebServicePort")
    public client_gen.LabWebService getLabWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "LabWebServicePort"), client_gen.LabWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GODSERVICE_EXCEPTION!= null) {
            throw GODSERVICE_EXCEPTION;
        }
        return GODSERVICE_WSDL_LOCATION;
    }

}
