
package client_gen;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LabWebService", targetNamespace = "http://server/")
@XmlSeeAlso({
    client_gen.ObjectFactory.class
})
public interface LabWebService {


    /**
     * 
     * @param name
     * @return
     *     returns java.util.List<client_gen.God>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGodByName", targetNamespace = "http://server/", className = "client_gen.GetGodByName")
    @ResponseWrapper(localName = "getGodByNameResponse", targetNamespace = "http://server/", className = "client_gen.GetGodByNameResponse")
    @Action(input = "http://server/LabWebService/getGodByNameRequest", output = "http://server/LabWebService/getGodByNameResponse")
    public List<client_gen.God> getGodByName(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param culture
     * @return
     *     returns java.util.List<client_gen.God>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGodsByCulture", targetNamespace = "http://server/", className = "client_gen.GetGodsByCulture")
    @ResponseWrapper(localName = "getGodsByCultureResponse", targetNamespace = "http://server/", className = "client_gen.GetGodsByCultureResponse")
    @Action(input = "http://server/LabWebService/getGodsByCultureRequest", output = "http://server/LabWebService/getGodsByCultureResponse")
    public List<client_gen.God> getGodsByCulture(
        @WebParam(name = "culture", targetNamespace = "")
        String culture);

    /**
     * 
     * @return
     *     returns java.util.List<client_gen.God>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllGods", targetNamespace = "http://server/", className = "client_gen.GetAllGods")
    @ResponseWrapper(localName = "getAllGodsResponse", targetNamespace = "http://server/", className = "client_gen.GetAllGodsResponse")
    @Action(input = "http://server/LabWebService/getAllGodsRequest", output = "http://server/LabWebService/getAllGodsResponse")
    public List<client_gen.God> getAllGods();

    /**
     * 
     * @param id
     * @return
     *     returns java.util.List<client_gen.God>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGodsById", targetNamespace = "http://server/", className = "client_gen.GetGodsById")
    @ResponseWrapper(localName = "getGodsByIdResponse", targetNamespace = "http://server/", className = "client_gen.GetGodsByIdResponse")
    @Action(input = "http://server/LabWebService/getGodsByIdRequest", output = "http://server/LabWebService/getGodsByIdResponse")
    public List<client_gen.God> getGodsById(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param godOf
     * @return
     *     returns java.util.List<client_gen.God>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGodsByGodOf", targetNamespace = "http://server/", className = "client_gen.GetGodsByGodOf")
    @ResponseWrapper(localName = "getGodsByGodOfResponse", targetNamespace = "http://server/", className = "client_gen.GetGodsByGodOfResponse")
    @Action(input = "http://server/LabWebService/getGodsByGodOfRequest", output = "http://server/LabWebService/getGodsByGodOfResponse")
    public List<client_gen.God> getGodsByGodOf(
        @WebParam(name = "god_of", targetNamespace = "")
        String godOf);

    /**
     * 
     * @param culture
     * @param godOf
     * @return
     *     returns java.util.List<client_gen.God>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGodsByCultureAndGodOf", targetNamespace = "http://server/", className = "client_gen.GetGodsByCultureAndGodOf")
    @ResponseWrapper(localName = "getGodsByCultureAndGodOfResponse", targetNamespace = "http://server/", className = "client_gen.GetGodsByCultureAndGodOfResponse")
    @Action(input = "http://server/LabWebService/getGodsByCultureAndGodOfRequest", output = "http://server/LabWebService/getGodsByCultureAndGodOfResponse")
    public List<client_gen.God> getGodsByCultureAndGodOf(
        @WebParam(name = "culture", targetNamespace = "")
        String culture,
        @WebParam(name = "god_of", targetNamespace = "")
        String godOf);

    /**
     * 
     * @param culture
     * @param name
     * @return
     *     returns java.util.List<client_gen.God>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGodsByNameAndCulture", targetNamespace = "http://server/", className = "client_gen.GetGodsByNameAndCulture")
    @ResponseWrapper(localName = "getGodsByNameAndCultureResponse", targetNamespace = "http://server/", className = "client_gen.GetGodsByNameAndCultureResponse")
    @Action(input = "http://server/LabWebService/getGodsByNameAndCultureRequest", output = "http://server/LabWebService/getGodsByNameAndCultureResponse")
    public List<client_gen.God> getGodsByNameAndCulture(
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "culture", targetNamespace = "")
        String culture);

}
